dist: xenial
language: python
python: 3.7
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coverage
  - pip install codecov
script:
  - nosetests --with-coverage --cover-package=shippostbot
after_success:
  - codecov
