dist: xenial
language: python
python: 3.7
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  - coverage run --source shippostbot -m unittest
after_success:
  - codecov
